unique_ids:
  forms:
    Main: 5CDZJQRUATB64PCZT6FHRR27DZBXFVWT
    Main.beam: '1721363176264180796569390.1603'
  modules: {}
  server_modules:
    ServerModule1: '1721357327697320372607815.5835'
  assets:
    standard-page.html: MFO4D2LBFNQ7Y6DYFQU5X2GUXNE6JLIM
    theme.css: 7G6J7HJZIPGJXEI4DHOANGAKE5VGVRIQ
  scripts: {}
